// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module idct_Loop_VITIS_LOOP_59_2_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        DCAC_temp_address0,
        DCAC_temp_ce0,
        DCAC_temp_q0,
        DCAC_temp_address1,
        DCAC_temp_ce1,
        DCAC_temp_q1,
        workspace_address0,
        workspace_ce0,
        workspace_we0,
        workspace_d0,
        workspace_address1,
        workspace_ce1,
        workspace_we1,
        workspace_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 10'd1;
parameter    ap_ST_fsm_pp0_stage1 = 10'd2;
parameter    ap_ST_fsm_pp0_stage2 = 10'd4;
parameter    ap_ST_fsm_pp0_stage3 = 10'd8;
parameter    ap_ST_fsm_pp0_stage4 = 10'd16;
parameter    ap_ST_fsm_pp0_stage5 = 10'd32;
parameter    ap_ST_fsm_pp0_stage6 = 10'd64;
parameter    ap_ST_fsm_pp0_stage7 = 10'd128;
parameter    ap_ST_fsm_pp0_stage8 = 10'd256;
parameter    ap_ST_fsm_pp0_stage9 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [4:0] DCAC_temp_address0;
output   DCAC_temp_ce0;
input  [31:0] DCAC_temp_q0;
output  [4:0] DCAC_temp_address1;
output   DCAC_temp_ce1;
input  [31:0] DCAC_temp_q1;
output  [5:0] workspace_address0;
output   workspace_ce0;
output   workspace_we0;
output  [20:0] workspace_d0;
output  [5:0] workspace_address1;
output   workspace_ce1;
output   workspace_we1;
output  [20:0] workspace_d1;

reg ap_idle;
reg[4:0] DCAC_temp_address0;
reg DCAC_temp_ce0;
reg[4:0] DCAC_temp_address1;
reg DCAC_temp_ce1;
reg[5:0] workspace_address0;
reg workspace_ce0;
reg workspace_we0;
reg[20:0] workspace_d0;
reg[5:0] workspace_address1;
reg workspace_ce1;
reg workspace_we1;
reg[20:0] workspace_d1;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_state10_pp0_stage9_iter0;
wire    ap_block_state20_pp0_stage9_iter1;
wire    ap_block_pp0_stage9_subdone;
reg   [0:0] tmp_reg_1847;
reg    ap_condition_exit_pp0_iter0_stage9;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [3:0] col_1_reg_1829;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state11_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [3:0] col_1_reg_1829_pp0_iter1_reg;
wire   [2:0] empty_fu_396_p1;
reg   [2:0] empty_reg_1842;
reg   [2:0] empty_reg_1842_pp0_iter1_reg;
wire   [0:0] tmp_fu_400_p3;
wire   [1:0] empty_59_fu_408_p1;
reg   [1:0] empty_59_reg_1851;
wire   [4:0] and_ln_fu_441_p3;
reg   [4:0] and_ln_reg_1870;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state12_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_11001;
wire  signed [2:0] tmp_7_fu_449_p3;
reg  signed [2:0] tmp_7_reg_1888;
wire  signed [15:0] z2_fu_487_p1;
reg  signed [15:0] z2_reg_1904;
wire  signed [15:0] z3_fu_501_p1;
reg  signed [15:0] z3_reg_1910;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state13_pp0_stage2_iter1;
wire    ap_block_pp0_stage2_11001;
wire  signed [15:0] tmp0_1_fu_532_p1;
reg  signed [15:0] tmp0_1_reg_1926;
wire  signed [15:0] tmp1_1_fu_545_p1;
reg  signed [15:0] tmp1_1_reg_1932;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state14_pp0_stage3_iter1;
wire    ap_block_pp0_stage3_11001;
wire  signed [15:0] tmp2_1_fu_564_p1;
reg  signed [15:0] tmp2_1_reg_1948;
wire  signed [15:0] tmp3_1_fu_577_p1;
reg  signed [15:0] tmp3_1_reg_1954;
wire   [1:0] or_ln63_fu_581_p2;
reg   [1:0] or_ln63_reg_1960;
wire  signed [2:0] tmp_s_fu_586_p3;
reg  signed [2:0] tmp_s_reg_1967;
wire  signed [16:0] z3_1_fu_625_p2;
reg  signed [16:0] z3_1_reg_1983;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_state15_pp0_stage4_iter1;
wire    ap_block_pp0_stage4_11001;
wire  signed [16:0] z4_fu_638_p2;
reg  signed [16:0] z4_reg_1988;
wire  signed [15:0] tmp0_5_fu_669_p1;
reg  signed [15:0] tmp0_5_reg_2003;
wire  signed [15:0] tmp1_5_fu_682_p1;
reg  signed [15:0] tmp1_5_reg_2009;
wire  signed [30:0] grp_fu_1625_p3;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state6_pp0_stage5_iter0;
wire    ap_block_state16_pp0_stage5_iter1;
wire    ap_block_pp0_stage5_11001;
wire  signed [15:0] tmp2_5_fu_725_p1;
reg  signed [15:0] tmp2_5_reg_2045;
wire  signed [15:0] tmp3_5_fu_738_p1;
reg  signed [15:0] tmp3_5_reg_2051;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_state7_pp0_stage6_iter0;
wire    ap_block_state17_pp0_stage6_iter1;
wire    ap_block_pp0_stage6_11001;
wire  signed [30:0] grp_fu_1634_p3;
reg  signed [30:0] tmp2_reg_2067;
wire  signed [29:0] grp_fu_1642_p3;
reg  signed [29:0] tmp3_reg_2073;
wire  signed [15:0] z2_3_fu_776_p1;
reg  signed [15:0] z2_3_reg_2094;
wire  signed [15:0] z3_4_fu_789_p1;
reg  signed [15:0] z3_4_reg_2100;
wire  signed [16:0] z3_5_fu_802_p2;
reg  signed [16:0] z3_5_reg_2106;
wire  signed [16:0] z4_3_fu_815_p2;
reg  signed [16:0] z4_3_reg_2111;
wire   [15:0] trunc_ln70_fu_834_p1;
reg   [15:0] trunc_ln70_reg_2116;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_state8_pp0_stage7_iter0;
wire    ap_block_state18_pp0_stage7_iter1;
wire    ap_block_pp0_stage7_11001;
wire   [15:0] trunc_ln71_fu_847_p1;
reg   [15:0] trunc_ln71_reg_2121;
wire  signed [31:0] grp_fu_1658_p3;
reg  signed [31:0] z5_reg_2126;
wire  signed [30:0] grp_fu_1666_p3;
reg  signed [30:0] z1_2_reg_2132;
wire  signed [31:0] grp_fu_1650_p3;
reg  signed [31:0] z2_2_reg_2138;
wire   [16:0] sub_ln74_fu_888_p2;
reg   [16:0] sub_ln74_reg_2169;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_state9_pp0_stage8_iter0;
wire    ap_block_state19_pp0_stage8_iter1;
wire    ap_block_pp0_stage8_11001;
wire   [16:0] add_ln73_fu_894_p2;
reg   [16:0] add_ln73_reg_2174;
wire  signed [30:0] grp_fu_1674_p3;
reg  signed [30:0] add_ln111_reg_2184;
wire  signed [31:0] grp_fu_1682_p3;
reg  signed [31:0] z3_3_reg_2189;
wire   [15:0] trunc_ln70_1_fu_918_p1;
reg   [15:0] trunc_ln70_1_reg_2205;
wire   [15:0] trunc_ln71_1_fu_931_p1;
reg   [15:0] trunc_ln71_1_reg_2210;
wire  signed [31:0] grp_fu_1707_p3;
reg  signed [31:0] z4_2_reg_2215;
wire    ap_block_pp0_stage9_11001;
reg   [20:0] trunc_ln1_reg_2220;
reg   [20:0] trunc_ln2_reg_2225;
reg   [20:0] trunc_ln3_reg_2230;
reg   [20:0] trunc_ln4_reg_2235;
wire   [31:0] add_ln119_fu_1097_p2;
reg   [31:0] add_ln119_reg_2240;
reg   [20:0] trunc_ln7_reg_2246;
reg   [20:0] trunc_ln8_reg_2251;
wire  signed [31:0] grp_fu_1723_p3;
wire  signed [30:0] grp_fu_1731_p3;
reg  signed [30:0] z1_5_reg_2277;
wire  signed [31:0] grp_fu_1715_p3;
reg  signed [31:0] z2_5_reg_2283;
wire  signed [3:0] xor_ln116_fu_1160_p2;
reg  signed [3:0] xor_ln116_reg_2289;
wire  signed [4:0] zext_ln119_cast_fu_1174_p3;
reg  signed [4:0] zext_ln119_cast_reg_2295;
wire  signed [30:0] grp_fu_1739_p3;
wire  signed [30:0] grp_fu_1748_p3;
reg  signed [30:0] add_ln111_2_reg_2310;
wire  signed [31:0] grp_fu_1756_p3;
reg  signed [31:0] z3_7_reg_2315;
wire  signed [31:0] grp_fu_1764_p3;
reg  signed [31:0] z4_5_reg_2321;
reg   [20:0] trunc_ln5_reg_2327;
reg   [20:0] trunc_ln6_reg_2332;
wire  signed [30:0] grp_fu_1780_p3;
reg  signed [30:0] tmp2_4_reg_2337;
wire   [16:0] sub_ln74_1_fu_1244_p2;
reg   [16:0] sub_ln74_1_reg_2343;
wire   [30:0] tmp13_1_fu_1268_p2;
reg   [30:0] tmp13_1_reg_2348;
(* use_dsp48 = "no" *) wire   [31:0] tmp3_7_fu_1277_p2;
reg   [31:0] tmp3_7_reg_2353;
wire   [30:0] add_ln115_2_fu_1291_p2;
reg   [30:0] add_ln115_2_reg_2359;
wire   [2:0] or_ln59_fu_1309_p2;
reg   [2:0] or_ln59_reg_2364;
reg   [20:0] trunc_ln116_1_reg_2369;
reg   [20:0] trunc_ln117_1_reg_2374;
reg   [20:0] trunc_ln118_1_reg_2379;
reg   [20:0] trunc_ln119_1_reg_2384;
reg   [20:0] trunc_ln120_1_reg_2389;
reg   [20:0] trunc_ln121_1_reg_2394;
reg   [20:0] trunc_ln122_1_reg_2399;
wire   [5:0] col_cast23_fu_1515_p1;
reg   [5:0] col_cast23_reg_2404;
wire   [3:0] zext_ln119_1_fu_1569_p1;
reg   [3:0] zext_ln119_1_reg_2410;
wire  signed [4:0] zext_ln119_1_cast_fu_1572_p3;
reg  signed [4:0] zext_ln119_1_cast_reg_2415;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln63_1_fu_420_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln64_fu_429_p1;
wire   [63:0] zext_ln85_fu_460_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln86_fu_472_p1;
wire   [63:0] zext_ln87_fu_508_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln88_fu_513_p1;
wire   [63:0] zext_ln85_2_fu_598_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln86_2_fu_611_p1;
wire   [63:0] zext_ln87_2_fu_651_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] zext_ln88_2_fu_656_p1;
wire   [63:0] zext_ln63_5_fu_702_p1;
wire    ap_block_pp0_stage5;
wire   [63:0] zext_ln64_2_fu_711_p1;
wire   [63:0] zext_ln63_fu_742_p1;
wire    ap_block_pp0_stage6;
wire   [63:0] zext_ln71_fu_753_p1;
wire   [63:0] zext_ln63_3_fu_851_p1;
wire    ap_block_pp0_stage7;
wire   [63:0] zext_ln71_2_fu_862_p1;
wire   [63:0] zext_ln116_fu_1169_p1;
wire   [63:0] zext_ln118_fu_1185_p1;
wire   [63:0] col_cast32_fu_1193_p1;
wire   [63:0] zext_ln117_fu_1201_p1;
wire   [63:0] zext_ln122_fu_1304_p1;
wire   [63:0] zext_ln63_2_fu_1314_p1;
wire   [63:0] zext_ln120_fu_1524_p1;
wire   [63:0] zext_ln116_1_fu_1538_p1;
wire   [63:0] zext_ln119_fu_1546_p1;
wire   [63:0] zext_ln117_1_fu_1556_p1;
wire   [63:0] zext_ln121_fu_1564_p1;
wire   [63:0] zext_ln118_1_fu_1584_p1;
wire   [63:0] zext_ln119_2_fu_1589_p1;
wire   [63:0] zext_ln120_1_fu_1598_p1;
wire    ap_block_pp0_stage8;
wire   [63:0] zext_ln121_1_fu_1608_p1;
wire   [63:0] zext_ln122_1_fu_1620_p1;
wire    ap_block_pp0_stage9;
reg   [3:0] col_fu_110;
wire   [3:0] add_ln59_fu_1150_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_col_1;
wire  signed [3:0] tmp_4_cast_fu_412_p3;
wire  signed [4:0] sext_ln64_fu_425_p1;
wire   [0:0] tmp_1_fu_434_p3;
wire  signed [4:0] sext_ln85_fu_456_p1;
wire   [4:0] tmp_8_cast_fu_465_p3;
wire   [31:0] zext_ln63_4_fu_477_p1;
wire   [31:0] lshr_ln63_fu_481_p2;
wire   [31:0] zext_ln64_1_fu_491_p1;
wire   [31:0] lshr_ln64_fu_495_p2;
wire  signed [3:0] sext_ln87_2_fu_505_p1;
wire   [31:0] zext_ln85_1_fu_523_p1;
wire   [31:0] lshr_ln85_fu_526_p2;
wire   [31:0] zext_ln86_1_fu_536_p1;
wire   [31:0] lshr_ln86_fu_539_p2;
wire   [31:0] zext_ln87_1_fu_555_p1;
wire   [31:0] lshr_ln87_fu_558_p2;
wire   [31:0] zext_ln88_1_fu_568_p1;
wire   [31:0] lshr_ln88_fu_571_p2;
wire  signed [4:0] sext_ln85_1_fu_594_p1;
wire   [4:0] tmp_17_cast_fu_603_p3;
wire  signed [16:0] sext_ln47_5_fu_622_p1;
wire  signed [16:0] sext_ln47_3_fu_616_p1;
wire  signed [16:0] sext_ln47_7_fu_635_p1;
wire  signed [16:0] sext_ln47_4_fu_619_p1;
wire  signed [3:0] sext_ln87_3_fu_648_p1;
wire   [31:0] zext_ln85_3_fu_660_p1;
wire   [31:0] lshr_ln85_1_fu_663_p2;
wire   [31:0] zext_ln86_3_fu_673_p1;
wire   [31:0] lshr_ln86_1_fu_676_p2;
wire  signed [3:0] tmp_13_cast_fu_695_p3;
wire  signed [4:0] sext_ln64_1_fu_707_p1;
wire   [31:0] zext_ln87_3_fu_716_p1;
wire   [31:0] lshr_ln87_1_fu_719_p2;
wire   [31:0] zext_ln88_3_fu_729_p1;
wire   [31:0] lshr_ln88_1_fu_732_p2;
wire   [4:0] tmp_6_cast_fu_746_p3;
wire   [31:0] zext_ln63_6_fu_767_p1;
wire   [31:0] lshr_ln63_1_fu_770_p2;
wire   [31:0] zext_ln64_3_fu_780_p1;
wire   [31:0] lshr_ln64_1_fu_783_p2;
wire  signed [16:0] sext_ln47_14_fu_799_p1;
wire  signed [16:0] sext_ln47_12_fu_793_p1;
wire  signed [16:0] sext_ln47_16_fu_812_p1;
wire  signed [16:0] sext_ln47_13_fu_796_p1;
wire   [31:0] zext_ln70_fu_825_p1;
wire   [31:0] lshr_ln70_fu_828_p2;
wire   [31:0] zext_ln71_1_fu_838_p1;
wire   [31:0] lshr_ln71_fu_841_p2;
wire   [4:0] tmp_15_cast_fu_855_p3;
wire  signed [16:0] sext_ln71_fu_882_p1;
wire  signed [16:0] sext_ln73_fu_885_p1;
wire   [31:0] zext_ln70_1_fu_909_p1;
wire   [31:0] lshr_ln70_1_fu_912_p2;
wire   [31:0] zext_ln71_3_fu_922_p1;
wire   [31:0] lshr_ln71_1_fu_925_p2;
wire   [29:0] tmp0_fu_941_p3;
wire  signed [30:0] sext_ln77_fu_948_p1;
wire  signed [30:0] sext_ln47_1_fu_938_p1;
wire   [30:0] tmp13_fu_952_p2;
wire   [29:0] tmp1_fu_962_p3;
wire  signed [31:0] sext_ln74_fu_969_p1;
wire  signed [31:0] sext_ln47_fu_935_p1;
wire  signed [30:0] grp_fu_1690_p3;
wire  signed [31:0] grp_fu_1698_p3;
wire  signed [31:0] sext_ln108_fu_982_p1;
wire  signed [31:0] sext_ln111_fu_979_p1;
(* use_dsp48 = "no" *) wire   [29:0] tmp10_fu_999_p2;
wire  signed [30:0] sext_ln115_fu_1004_p1;
wire   [30:0] add_ln115_fu_1008_p2;
wire  signed [31:0] sext_ln116_fu_1014_p1;
(* use_dsp48 = "no" *) wire   [31:0] tmp3_3_fu_994_p2;
wire   [31:0] add_ln115_1_fu_1024_p2;
wire   [31:0] sub_ln116_fu_1018_p2;
(* use_dsp48 = "no" *) wire   [30:0] tmp11_fu_1050_p2;
wire  signed [31:0] sext_ln117_fu_1055_p1;
wire   [31:0] add_ln117_fu_1059_p2;
(* use_dsp48 = "no" *) wire   [31:0] tmp2_3_fu_985_p2;
wire   [31:0] add_ln117_1_fu_1071_p2;
wire   [31:0] sub_ln118_fu_1065_p2;
wire   [31:0] tmp12_fu_973_p2;
wire  signed [31:0] sext_ln47_10_fu_958_p1;
wire   [31:0] add_ln121_fu_1103_p2;
(* use_dsp48 = "no" *) wire   [31:0] tmp0_3_fu_989_p2;
wire   [31:0] add_ln121_1_fu_1115_p2;
wire   [31:0] sub_ln122_fu_1109_p2;
wire  signed [5:0] sext_ln116_1_fu_1165_p1;
wire  signed [5:0] sext_ln118_fu_1181_p1;
wire  signed [31:0] grp_fu_1772_p3;
(* use_dsp48 = "no" *) wire   [31:0] tmp1_3_fu_1197_p2;
wire   [31:0] add_ln119_1_fu_1210_p2;
wire   [31:0] sub_ln120_fu_1205_p2;
wire  signed [29:0] grp_fu_1788_p3;
wire  signed [16:0] sext_ln71_1_fu_1238_p1;
wire  signed [16:0] sext_ln73_1_fu_1241_p1;
wire   [16:0] add_ln73_1_fu_1250_p2;
wire   [29:0] tmp0_4_fu_1256_p3;
wire  signed [30:0] sext_ln77_1_fu_1264_p1;
wire  signed [30:0] sext_ln47_18_fu_1235_p1;
wire  signed [31:0] sext_ln111_1_fu_1274_p1;
(* use_dsp48 = "no" *) wire   [29:0] tmp10_1_fu_1282_p2;
wire  signed [30:0] sext_ln115_1_fu_1287_p1;
wire   [5:0] zext_ln122_cast_fu_1297_p3;
wire   [29:0] tmp1_4_fu_1325_p3;
wire  signed [31:0] sext_ln74_1_fu_1332_p1;
wire  signed [31:0] sext_ln47_9_fu_1319_p1;
wire  signed [30:0] grp_fu_1798_p3;
wire  signed [31:0] grp_fu_1814_p3;
wire  signed [31:0] sext_ln108_1_fu_1342_p1;
wire  signed [31:0] grp_fu_1806_p3;
wire  signed [31:0] sext_ln116_2_fu_1358_p1;
wire   [31:0] add_ln115_3_fu_1366_p2;
wire   [31:0] sub_ln116_1_fu_1361_p2;
(* use_dsp48 = "no" *) wire   [30:0] tmp11_1_fu_1392_p2;
wire  signed [31:0] sext_ln117_1_fu_1397_p1;
wire   [31:0] add_ln117_2_fu_1401_p2;
(* use_dsp48 = "no" *) wire   [31:0] tmp2_7_fu_1345_p2;
wire   [31:0] add_ln117_3_fu_1413_p2;
wire   [31:0] sub_ln118_1_fu_1407_p2;
wire   [31:0] tmp12_1_fu_1336_p2;
wire   [31:0] add_ln119_2_fu_1439_p2;
(* use_dsp48 = "no" *) wire   [31:0] tmp1_7_fu_1354_p2;
wire   [31:0] add_ln119_3_fu_1451_p2;
wire   [31:0] sub_ln120_1_fu_1445_p2;
wire  signed [31:0] sext_ln47_19_fu_1322_p1;
wire   [31:0] add_ln121_2_fu_1477_p2;
(* use_dsp48 = "no" *) wire   [31:0] tmp0_7_fu_1349_p2;
wire   [31:0] add_ln121_3_fu_1489_p2;
wire   [31:0] sub_ln122_1_fu_1483_p2;
wire   [5:0] add_ln120_fu_1518_p2;
wire   [3:0] add_ln116_fu_1529_p2;
wire  signed [5:0] sext_ln116_3_fu_1534_p1;
wire   [4:0] col_cast60_fu_1543_p1;
wire   [4:0] add_ln117_4_fu_1550_p2;
wire  signed [4:0] sext_ln121_fu_1561_p1;
wire  signed [5:0] sext_ln118_1_fu_1580_p1;
wire   [5:0] add_ln120_1_fu_1593_p2;
wire   [5:0] add_ln121_4_fu_1603_p2;
wire   [5:0] zext_ln122_1_cast_fu_1613_p3;
wire   [12:0] grp_fu_1625_p2;
wire  signed [14:0] grp_fu_1634_p1;
wire   [12:0] grp_fu_1642_p1;
wire   [29:0] grp_fu_1642_p2;
wire  signed [15:0] grp_fu_1650_p0;
wire  signed [15:0] grp_fu_1650_p1;
wire  signed [15:0] grp_fu_1650_p2;
wire   [13:0] grp_fu_1658_p2;
wire  signed [15:0] grp_fu_1666_p0;
wire  signed [15:0] grp_fu_1666_p1;
wire  signed [13:0] grp_fu_1666_p2;
wire   [13:0] grp_fu_1674_p1;
wire  signed [14:0] grp_fu_1682_p1;
wire   [11:0] grp_fu_1690_p1;
wire   [14:0] grp_fu_1698_p1;
wire  signed [12:0] grp_fu_1707_p1;
wire  signed [15:0] grp_fu_1715_p0;
wire  signed [15:0] grp_fu_1715_p1;
wire  signed [15:0] grp_fu_1715_p2;
wire   [13:0] grp_fu_1723_p2;
wire  signed [15:0] grp_fu_1731_p0;
wire  signed [15:0] grp_fu_1731_p1;
wire  signed [13:0] grp_fu_1731_p2;
wire   [12:0] grp_fu_1739_p2;
wire   [13:0] grp_fu_1748_p1;
wire  signed [14:0] grp_fu_1756_p1;
wire  signed [12:0] grp_fu_1764_p1;
wire   [14:0] grp_fu_1772_p1;
wire  signed [14:0] grp_fu_1780_p1;
wire   [12:0] grp_fu_1788_p1;
wire   [29:0] grp_fu_1788_p2;
wire   [11:0] grp_fu_1798_p1;
wire   [14:0] grp_fu_1806_p1;
wire   [14:0] grp_fu_1814_p1;
reg    grp_fu_1625_ce;
reg    grp_fu_1634_ce;
reg    grp_fu_1642_ce;
reg    grp_fu_1650_ce;
reg    grp_fu_1658_ce;
reg    grp_fu_1666_ce;
reg    grp_fu_1674_ce;
reg    grp_fu_1682_ce;
reg    grp_fu_1690_ce;
reg    grp_fu_1698_ce;
reg    grp_fu_1707_ce;
reg    grp_fu_1715_ce;
reg    grp_fu_1723_ce;
reg    grp_fu_1731_ce;
reg    grp_fu_1739_ce;
reg    grp_fu_1748_ce;
reg    grp_fu_1756_ce;
reg    grp_fu_1764_ce;
reg    grp_fu_1772_ce;
reg    grp_fu_1780_ce;
reg    grp_fu_1788_ce;
reg    grp_fu_1798_ce;
reg    grp_fu_1806_ce;
reg    grp_fu_1814_ce;
wire    ap_continue_int;
reg    ap_done_int;
reg   [9:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_pp0_stage8_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_352;
reg    ap_condition_1685;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

idct_am_addmul_16s_16s_13ns_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 31 ))
am_addmul_16s_16s_13ns_31_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z3_reg_1910),
    .din1(z2_reg_1904),
    .din2(grp_fu_1625_p2),
    .ce(grp_fu_1625_ce),
    .dout(grp_fu_1625_p3)
);

idct_mac_muladd_16s_15s_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_15s_31s_31_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z3_reg_1910),
    .din1(grp_fu_1634_p1),
    .din2(grp_fu_1625_p3),
    .ce(grp_fu_1634_ce),
    .dout(grp_fu_1634_p3)
);

idct_mac_muladd_16s_13ns_30ns_30_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
mac_muladd_16s_13ns_30ns_30_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z2_reg_1904),
    .din1(grp_fu_1642_p1),
    .din2(grp_fu_1642_p2),
    .ce(grp_fu_1642_ce),
    .dout(grp_fu_1642_p3)
);

idct_am_addmul_16s_16s_16s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
am_addmul_16s_16s_16s_32_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1650_p0),
    .din1(grp_fu_1650_p1),
    .din2(grp_fu_1650_p2),
    .ce(grp_fu_1650_ce),
    .dout(grp_fu_1650_p3)
);

idct_am_addmul_17s_17s_14ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 17 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
am_addmul_17s_17s_14ns_32_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z4_fu_638_p2),
    .din1(z3_1_fu_625_p2),
    .din2(grp_fu_1658_p2),
    .ce(grp_fu_1658_ce),
    .dout(grp_fu_1658_p3)
);

idct_am_addmul_16s_16s_14s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 31 ))
am_addmul_16s_16s_14s_31_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1666_p0),
    .din1(grp_fu_1666_p1),
    .din2(grp_fu_1666_p2),
    .ce(grp_fu_1666_ce),
    .dout(grp_fu_1666_p3)
);

idct_mac_muladd_16s_14ns_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_14ns_31s_31_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp3_1_reg_1954),
    .din1(grp_fu_1674_p1),
    .din2(grp_fu_1666_p3),
    .ce(grp_fu_1674_ce),
    .dout(grp_fu_1674_p3)
);

idct_mac_muladd_17s_15s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_17s_15s_32s_32_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z3_1_reg_1983),
    .din1(grp_fu_1682_p1),
    .din2(grp_fu_1658_p3),
    .ce(grp_fu_1682_ce),
    .dout(grp_fu_1682_p3)
);

idct_mac_muladd_16s_12ns_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_12ns_31s_31_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp0_1_reg_1926),
    .din1(grp_fu_1690_p1),
    .din2(z1_2_reg_2132),
    .ce(grp_fu_1690_ce),
    .dout(grp_fu_1690_p3)
);

idct_mac_muladd_16s_15ns_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_15ns_32s_32_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp2_1_reg_1948),
    .din1(grp_fu_1698_p1),
    .din2(grp_fu_1682_p3),
    .ce(grp_fu_1698_ce),
    .dout(grp_fu_1698_p3)
);

idct_mac_muladd_17s_13s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_17s_13s_32s_32_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z4_reg_1988),
    .din1(grp_fu_1707_p1),
    .din2(z5_reg_2126),
    .ce(grp_fu_1707_ce),
    .dout(grp_fu_1707_p3)
);

idct_am_addmul_16s_16s_16s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
am_addmul_16s_16s_16s_32_4_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1715_p0),
    .din1(grp_fu_1715_p1),
    .din2(grp_fu_1715_p2),
    .ce(grp_fu_1715_ce),
    .dout(grp_fu_1715_p3)
);

idct_am_addmul_17s_17s_14ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 17 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
am_addmul_17s_17s_14ns_32_4_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z4_3_fu_815_p2),
    .din1(z3_5_fu_802_p2),
    .din2(grp_fu_1723_p2),
    .ce(grp_fu_1723_ce),
    .dout(grp_fu_1723_p3)
);

idct_am_addmul_16s_16s_14s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 31 ))
am_addmul_16s_16s_14s_31_4_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1731_p0),
    .din1(grp_fu_1731_p1),
    .din2(grp_fu_1731_p2),
    .ce(grp_fu_1731_ce),
    .dout(grp_fu_1731_p3)
);

idct_am_addmul_16s_16s_13ns_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 31 ))
am_addmul_16s_16s_13ns_31_4_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z3_4_reg_2100),
    .din1(z2_3_reg_2094),
    .din2(grp_fu_1739_p2),
    .ce(grp_fu_1739_ce),
    .dout(grp_fu_1739_p3)
);

idct_mac_muladd_16s_14ns_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_14ns_31s_31_4_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp3_5_reg_2051),
    .din1(grp_fu_1748_p1),
    .din2(grp_fu_1731_p3),
    .ce(grp_fu_1748_ce),
    .dout(grp_fu_1748_p3)
);

idct_mac_muladd_17s_15s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_17s_15s_32s_32_4_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z3_5_reg_2106),
    .din1(grp_fu_1756_p1),
    .din2(grp_fu_1723_p3),
    .ce(grp_fu_1756_ce),
    .dout(grp_fu_1756_p3)
);

idct_mac_muladd_17s_13s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_17s_13s_32s_32_4_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z4_3_reg_2111),
    .din1(grp_fu_1764_p1),
    .din2(grp_fu_1723_p3),
    .ce(grp_fu_1764_ce),
    .dout(grp_fu_1764_p3)
);

idct_mac_muladd_16s_15ns_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_15ns_32s_32_4_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp1_1_reg_1932),
    .din1(grp_fu_1772_p1),
    .din2(z4_2_reg_2215),
    .ce(grp_fu_1772_ce),
    .dout(grp_fu_1772_p3)
);

idct_mac_muladd_16s_15s_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_15s_31s_31_4_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z3_4_reg_2100),
    .din1(grp_fu_1780_p1),
    .din2(grp_fu_1739_p3),
    .ce(grp_fu_1780_ce),
    .dout(grp_fu_1780_p3)
);

idct_mac_muladd_16s_13ns_30ns_30_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
mac_muladd_16s_13ns_30ns_30_4_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(z2_3_reg_2094),
    .din1(grp_fu_1788_p1),
    .din2(grp_fu_1788_p2),
    .ce(grp_fu_1788_ce),
    .dout(grp_fu_1788_p3)
);

idct_mac_muladd_16s_12ns_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_12ns_31s_31_4_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp0_5_reg_2003),
    .din1(grp_fu_1798_p1),
    .din2(z1_5_reg_2277),
    .ce(grp_fu_1798_ce),
    .dout(grp_fu_1798_p3)
);

idct_mac_muladd_16s_15ns_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_15ns_32s_32_4_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp1_5_reg_2009),
    .din1(grp_fu_1806_p1),
    .din2(z4_5_reg_2321),
    .ce(grp_fu_1806_ce),
    .dout(grp_fu_1806_p3)
);

idct_mac_muladd_16s_15ns_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_15ns_32s_32_4_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp2_5_reg_2045),
    .din1(grp_fu_1814_p1),
    .din2(z3_7_reg_2315),
    .ce(grp_fu_1814_ce),
    .dout(grp_fu_1814_p3)
);

idct_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage9),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage9_subdone) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage9)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage9_subdone) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if ((1'b1 == ap_condition_1685)) begin
            col_fu_110 <= 4'd0;
        end else if ((1'b1 == ap_condition_352)) begin
            col_fu_110 <= add_ln59_fu_1150_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln111_2_reg_2310 <= grp_fu_1748_p3;
        z3_7_reg_2315 <= grp_fu_1756_p3;
        z4_5_reg_2321 <= grp_fu_1764_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_1847 == 1'd0) & (1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        add_ln111_reg_2184 <= grp_fu_1674_p3;
        z3_3_reg_2189 <= grp_fu_1682_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln115_2_reg_2359 <= add_ln115_2_fu_1291_p2;
        sub_ln74_1_reg_2343 <= sub_ln74_1_fu_1244_p2;
        tmp13_1_reg_2348 <= tmp13_1_fu_1268_p2;
        tmp3_7_reg_2353 <= tmp3_7_fu_1277_p2;
        trunc_ln5_reg_2327 <= {{add_ln119_1_fu_1210_p2[31:11]}};
        trunc_ln6_reg_2332 <= {{sub_ln120_fu_1205_p2[31:11]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_1847 == 1'd0) & (1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        add_ln119_reg_2240 <= add_ln119_fu_1097_p2;
        trunc_ln1_reg_2220 <= {{add_ln115_1_fu_1024_p2[31:11]}};
        trunc_ln2_reg_2225 <= {{sub_ln116_fu_1018_p2[31:11]}};
        trunc_ln3_reg_2230 <= {{add_ln117_1_fu_1071_p2[31:11]}};
        trunc_ln4_reg_2235 <= {{sub_ln118_fu_1065_p2[31:11]}};
        trunc_ln7_reg_2246 <= {{add_ln121_1_fu_1115_p2[31:11]}};
        trunc_ln8_reg_2251 <= {{sub_ln122_fu_1109_p2[31:11]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_1847 == 1'd0) & (1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        add_ln73_reg_2174 <= add_ln73_fu_894_p2;
        sub_ln74_reg_2169 <= sub_ln74_fu_888_p2;
        trunc_ln70_1_reg_2205 <= trunc_ln70_1_fu_918_p1;
        trunc_ln71_1_reg_2210 <= trunc_ln71_1_fu_931_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_1847 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        and_ln_reg_1870[4] <= and_ln_fu_441_p3[4];
        tmp_7_reg_1888[1 : 0] <= tmp_7_fu_449_p3[1 : 0];
        z2_reg_1904 <= z2_fu_487_p1;
        z3_reg_1910 <= z3_fu_501_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_1_reg_1829 <= ap_sig_allocacmp_col_1;
        col_1_reg_1829_pp0_iter1_reg <= col_1_reg_1829;
        empty_reg_1842 <= empty_fu_396_p1;
        empty_reg_1842_pp0_iter1_reg <= empty_reg_1842;
        tmp_reg_1847 <= ap_sig_allocacmp_col_1[32'd3];
        xor_ln116_reg_2289 <= xor_ln116_fu_1160_p2;
        zext_ln119_cast_reg_2295[3 : 0] <= zext_ln119_cast_fu_1174_p3[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        col_cast23_reg_2404[3 : 0] <= col_cast23_fu_1515_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_400_p3 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_59_reg_1851 <= empty_59_fu_408_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        or_ln59_reg_2364[2 : 1] <= or_ln59_fu_1309_p2[2 : 1];
        trunc_ln116_1_reg_2369 <= {{sub_ln116_1_fu_1361_p2[31:11]}};
        trunc_ln117_1_reg_2374 <= {{add_ln117_3_fu_1413_p2[31:11]}};
        trunc_ln118_1_reg_2379 <= {{sub_ln118_1_fu_1407_p2[31:11]}};
        trunc_ln119_1_reg_2384 <= {{add_ln119_3_fu_1451_p2[31:11]}};
        trunc_ln120_1_reg_2389 <= {{sub_ln120_1_fu_1445_p2[31:11]}};
        trunc_ln121_1_reg_2394 <= {{add_ln121_3_fu_1489_p2[31:11]}};
        trunc_ln122_1_reg_2399 <= {{sub_ln122_1_fu_1483_p2[31:11]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_1847 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        or_ln63_reg_1960[1] <= or_ln63_fu_581_p2[1];
        tmp2_1_reg_1948 <= tmp2_1_fu_564_p1;
        tmp3_1_reg_1954 <= tmp3_1_fu_577_p1;
        tmp_s_reg_1967[1] <= tmp_s_fu_586_p3[1];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_1847 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp0_1_reg_1926 <= tmp0_1_fu_532_p1;
        tmp1_1_reg_1932 <= tmp1_1_fu_545_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_1847 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        tmp0_5_reg_2003 <= tmp0_5_fu_669_p1;
        tmp1_5_reg_2009 <= tmp1_5_fu_682_p1;
        z3_1_reg_1983 <= z3_1_fu_625_p2;
        z4_reg_1988 <= z4_fu_638_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp2_4_reg_2337 <= grp_fu_1780_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_1847 == 1'd0) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        tmp2_5_reg_2045 <= tmp2_5_fu_725_p1;
        tmp3_5_reg_2051 <= tmp3_5_fu_738_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_1847 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        tmp2_reg_2067 <= grp_fu_1634_p3;
        tmp3_reg_2073 <= grp_fu_1642_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_1847 == 1'd0) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        trunc_ln70_reg_2116 <= trunc_ln70_fu_834_p1;
        trunc_ln71_reg_2121 <= trunc_ln71_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_1847 == 1'd0) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        z1_2_reg_2132 <= grp_fu_1666_p3;
        z2_2_reg_2138 <= grp_fu_1650_p3;
        z5_reg_2126 <= grp_fu_1658_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_1847 == 1'd0) & (1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        z1_5_reg_2277 <= grp_fu_1731_p3;
        z2_5_reg_2283 <= grp_fu_1715_p3;
        z4_2_reg_2215 <= grp_fu_1707_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_1847 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        z2_3_reg_2094 <= z2_3_fu_776_p1;
        z3_4_reg_2100 <= z3_4_fu_789_p1;
        z3_5_reg_2106 <= z3_5_fu_802_p2;
        z4_3_reg_2111 <= z4_3_fu_815_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        zext_ln119_1_cast_reg_2415[2 : 1] <= zext_ln119_1_cast_fu_1572_p3[2 : 1];
        zext_ln119_1_reg_2410[2 : 1] <= zext_ln119_1_fu_1569_p1[2 : 1];
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            DCAC_temp_address0 = zext_ln71_2_fu_862_p1;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            DCAC_temp_address0 = zext_ln71_fu_753_p1;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            DCAC_temp_address0 = zext_ln64_2_fu_711_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            DCAC_temp_address0 = zext_ln88_2_fu_656_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            DCAC_temp_address0 = zext_ln86_2_fu_611_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            DCAC_temp_address0 = zext_ln88_fu_513_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            DCAC_temp_address0 = zext_ln86_fu_472_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DCAC_temp_address0 = zext_ln64_fu_429_p1;
        end else begin
            DCAC_temp_address0 = 'bx;
        end
    end else begin
        DCAC_temp_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            DCAC_temp_address1 = zext_ln63_3_fu_851_p1;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            DCAC_temp_address1 = zext_ln63_fu_742_p1;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            DCAC_temp_address1 = zext_ln63_5_fu_702_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            DCAC_temp_address1 = zext_ln87_2_fu_651_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            DCAC_temp_address1 = zext_ln85_2_fu_598_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            DCAC_temp_address1 = zext_ln87_fu_508_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            DCAC_temp_address1 = zext_ln85_fu_460_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DCAC_temp_address1 = zext_ln63_1_fu_420_p1;
        end else begin
            DCAC_temp_address1 = 'bx;
        end
    end else begin
        DCAC_temp_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        DCAC_temp_ce0 = 1'b1;
    end else begin
        DCAC_temp_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        DCAC_temp_ce1 = 1'b1;
    end else begin
        DCAC_temp_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_1847 == 1'd1) & (1'b0 == ap_block_pp0_stage9_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        ap_condition_exit_pp0_iter0_stage9 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage9 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage9_subdone) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage9_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_col_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_col_1 = col_fu_110;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_fu_1625_ce = 1'b1;
    end else begin
        grp_fu_1625_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_1634_ce = 1'b1;
    end else begin
        grp_fu_1634_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_1642_ce = 1'b1;
    end else begin
        grp_fu_1642_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        grp_fu_1650_ce = 1'b1;
    end else begin
        grp_fu_1650_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        grp_fu_1658_ce = 1'b1;
    end else begin
        grp_fu_1658_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        grp_fu_1666_ce = 1'b1;
    end else begin
        grp_fu_1666_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        grp_fu_1674_ce = 1'b1;
    end else begin
        grp_fu_1674_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        grp_fu_1682_ce = 1'b1;
    end else begin
        grp_fu_1682_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)))) begin
        grp_fu_1690_ce = 1'b1;
    end else begin
        grp_fu_1690_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)))) begin
        grp_fu_1698_ce = 1'b1;
    end else begin
        grp_fu_1698_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)))) begin
        grp_fu_1707_ce = 1'b1;
    end else begin
        grp_fu_1707_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)))) begin
        grp_fu_1715_ce = 1'b1;
    end else begin
        grp_fu_1715_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)))) begin
        grp_fu_1723_ce = 1'b1;
    end else begin
        grp_fu_1723_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)))) begin
        grp_fu_1731_ce = 1'b1;
    end else begin
        grp_fu_1731_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)))) begin
        grp_fu_1739_ce = 1'b1;
    end else begin
        grp_fu_1739_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)))) begin
        grp_fu_1748_ce = 1'b1;
    end else begin
        grp_fu_1748_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)))) begin
        grp_fu_1756_ce = 1'b1;
    end else begin
        grp_fu_1756_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)))) begin
        grp_fu_1764_ce = 1'b1;
    end else begin
        grp_fu_1764_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_1772_ce = 1'b1;
    end else begin
        grp_fu_1772_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_1780_ce = 1'b1;
    end else begin
        grp_fu_1780_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_1788_ce = 1'b1;
    end else begin
        grp_fu_1788_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_1798_ce = 1'b1;
    end else begin
        grp_fu_1798_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_1806_ce = 1'b1;
    end else begin
        grp_fu_1806_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_1814_ce = 1'b1;
    end else begin
        grp_fu_1814_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            workspace_address0 = zext_ln120_1_fu_1598_p1;
        end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            workspace_address0 = zext_ln119_2_fu_1589_p1;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            workspace_address0 = zext_ln121_fu_1564_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            workspace_address0 = zext_ln117_1_fu_1556_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            workspace_address0 = zext_ln116_1_fu_1538_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            workspace_address0 = zext_ln63_2_fu_1314_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            workspace_address0 = zext_ln117_fu_1201_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            workspace_address0 = zext_ln118_fu_1185_p1;
        end else begin
            workspace_address0 = 'bx;
        end
    end else begin
        workspace_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            workspace_address1 = zext_ln122_1_fu_1620_p1;
        end else if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            workspace_address1 = zext_ln121_1_fu_1608_p1;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            workspace_address1 = zext_ln118_1_fu_1584_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            workspace_address1 = zext_ln119_fu_1546_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            workspace_address1 = zext_ln120_fu_1524_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            workspace_address1 = zext_ln122_fu_1304_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            workspace_address1 = col_cast32_fu_1193_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            workspace_address1 = zext_ln116_fu_1169_p1;
        end else begin
            workspace_address1 = 'bx;
        end
    end else begin
        workspace_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        workspace_ce0 = 1'b1;
    end else begin
        workspace_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        workspace_ce1 = 1'b1;
    end else begin
        workspace_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            workspace_d0 = trunc_ln120_1_reg_2389;
        end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            workspace_d0 = trunc_ln119_1_reg_2384;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            workspace_d0 = trunc_ln7_reg_2246;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            workspace_d0 = trunc_ln117_1_reg_2374;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            workspace_d0 = trunc_ln116_1_reg_2369;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            workspace_d0 = {{add_ln115_3_fu_1366_p2[31:11]}};
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            workspace_d0 = trunc_ln3_reg_2230;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            workspace_d0 = trunc_ln4_reg_2235;
        end else begin
            workspace_d0 = 'bx;
        end
    end else begin
        workspace_d0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            workspace_d1 = trunc_ln122_1_reg_2399;
        end else if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            workspace_d1 = trunc_ln121_1_reg_2394;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            workspace_d1 = trunc_ln118_1_reg_2379;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            workspace_d1 = trunc_ln5_reg_2327;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            workspace_d1 = trunc_ln6_reg_2332;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            workspace_d1 = trunc_ln8_reg_2251;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            workspace_d1 = trunc_ln1_reg_2220;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            workspace_d1 = trunc_ln2_reg_2225;
        end else begin
            workspace_d1 = 'bx;
        end
    end else begin
        workspace_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        workspace_we0 = 1'b1;
    end else begin
        workspace_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        workspace_we1 = 1'b1;
    end else begin
        workspace_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln115_1_fu_1024_p2 = ($signed(tmp3_3_fu_994_p2) + $signed(sext_ln116_fu_1014_p1));

assign add_ln115_2_fu_1291_p2 = ($signed(sext_ln77_1_fu_1264_p1) + $signed(sext_ln115_1_fu_1287_p1));

assign add_ln115_3_fu_1366_p2 = ($signed(tmp3_7_reg_2353) + $signed(sext_ln116_2_fu_1358_p1));

assign add_ln115_fu_1008_p2 = ($signed(sext_ln77_fu_948_p1) + $signed(sext_ln115_fu_1004_p1));

assign add_ln116_fu_1529_p2 = ($signed(col_1_reg_1829_pp0_iter1_reg) + $signed(4'd9));

assign add_ln117_1_fu_1071_p2 = (tmp2_3_fu_985_p2 + add_ln117_fu_1059_p2);

assign add_ln117_2_fu_1401_p2 = ($signed(sext_ln74_1_fu_1332_p1) + $signed(sext_ln117_1_fu_1397_p1));

assign add_ln117_3_fu_1413_p2 = (tmp2_7_fu_1345_p2 + add_ln117_2_fu_1401_p2);

assign add_ln117_4_fu_1550_p2 = (col_cast60_fu_1543_p1 + 5'd9);

assign add_ln117_fu_1059_p2 = ($signed(sext_ln74_fu_969_p1) + $signed(sext_ln117_fu_1055_p1));

assign add_ln119_1_fu_1210_p2 = (tmp1_3_fu_1197_p2 + add_ln119_reg_2240);

assign add_ln119_2_fu_1439_p2 = (tmp12_1_fu_1336_p2 + 32'd1024);

assign add_ln119_3_fu_1451_p2 = (tmp1_7_fu_1354_p2 + add_ln119_2_fu_1439_p2);

assign add_ln119_fu_1097_p2 = (tmp12_fu_973_p2 + 32'd1024);

assign add_ln120_1_fu_1593_p2 = ($signed(col_cast23_reg_2404) + $signed(6'd41));

assign add_ln120_fu_1518_p2 = ($signed(col_cast23_fu_1515_p1) + $signed(6'd40));

assign add_ln121_1_fu_1115_p2 = (tmp0_3_fu_989_p2 + add_ln121_fu_1103_p2);

assign add_ln121_2_fu_1477_p2 = ($signed(sext_ln47_19_fu_1322_p1) + $signed(32'd1024));

assign add_ln121_3_fu_1489_p2 = (tmp0_7_fu_1349_p2 + add_ln121_2_fu_1477_p2);

assign add_ln121_4_fu_1603_p2 = (col_cast23_reg_2404 + 6'd25);

assign add_ln121_fu_1103_p2 = ($signed(sext_ln47_10_fu_958_p1) + $signed(32'd1024));

assign add_ln59_fu_1150_p2 = (col_1_reg_1829 + 4'd2);

assign add_ln73_1_fu_1250_p2 = ($signed(sext_ln73_1_fu_1241_p1) + $signed(sext_ln71_1_fu_1238_p1));

assign add_ln73_fu_894_p2 = ($signed(sext_ln73_fu_885_p1) + $signed(sext_ln71_fu_882_p1));

assign and_ln_fu_441_p3 = {{tmp_1_fu_434_p3}, {4'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_done_reg == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_done_reg == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage9_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage5_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage6_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage7_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage8_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_block_state20_pp0_stage9_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage8_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1685 = ((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_352 = ((tmp_reg_1847 == 1'd0) & (1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage9;

assign col_cast23_fu_1515_p1 = col_1_reg_1829_pp0_iter1_reg;

assign col_cast32_fu_1193_p1 = col_1_reg_1829_pp0_iter1_reg;

assign col_cast60_fu_1543_p1 = col_1_reg_1829_pp0_iter1_reg;

assign empty_59_fu_408_p1 = ap_sig_allocacmp_col_1[1:0];

assign empty_fu_396_p1 = ap_sig_allocacmp_col_1[2:0];

assign grp_fu_1625_p2 = 31'd4433;

assign grp_fu_1634_p1 = 31'd2147468511;

assign grp_fu_1642_p1 = 30'd6270;

assign grp_fu_1642_p2 = grp_fu_1625_p3[29:0];

assign grp_fu_1650_p0 = sext_ln47_5_fu_622_p1;

assign grp_fu_1650_p1 = sext_ln47_4_fu_619_p1;

assign grp_fu_1650_p2 = 32'd4294946301;

assign grp_fu_1658_p2 = 32'd9633;

assign grp_fu_1666_p0 = sext_ln47_7_fu_635_p1;

assign grp_fu_1666_p1 = sext_ln47_3_fu_616_p1;

assign grp_fu_1666_p2 = 31'd2147476275;

assign grp_fu_1674_p1 = 31'd12299;

assign grp_fu_1682_p1 = 32'd4294951227;

assign grp_fu_1690_p1 = 29'd2446;

assign grp_fu_1698_p1 = 32'd25172;

assign grp_fu_1707_p1 = 30'd1073738628;

assign grp_fu_1715_p0 = sext_ln47_14_fu_799_p1;

assign grp_fu_1715_p1 = sext_ln47_13_fu_796_p1;

assign grp_fu_1715_p2 = 32'd4294946301;

assign grp_fu_1723_p2 = 32'd9633;

assign grp_fu_1731_p0 = sext_ln47_16_fu_812_p1;

assign grp_fu_1731_p1 = sext_ln47_12_fu_793_p1;

assign grp_fu_1731_p2 = 31'd2147476275;

assign grp_fu_1739_p2 = 31'd4433;

assign grp_fu_1748_p1 = 31'd12299;

assign grp_fu_1756_p1 = 32'd4294951227;

assign grp_fu_1764_p1 = 30'd1073738628;

assign grp_fu_1772_p1 = 32'd16819;

assign grp_fu_1780_p1 = 31'd2147468511;

assign grp_fu_1788_p1 = 30'd6270;

assign grp_fu_1788_p2 = grp_fu_1739_p3[29:0];

assign grp_fu_1798_p1 = 29'd2446;

assign grp_fu_1806_p1 = 32'd16819;

assign grp_fu_1814_p1 = 32'd25172;

assign lshr_ln63_1_fu_770_p2 = DCAC_temp_q1 >> zext_ln63_6_fu_767_p1;

assign lshr_ln63_fu_481_p2 = DCAC_temp_q1 >> zext_ln63_4_fu_477_p1;

assign lshr_ln64_1_fu_783_p2 = DCAC_temp_q0 >> zext_ln64_3_fu_780_p1;

assign lshr_ln64_fu_495_p2 = DCAC_temp_q0 >> zext_ln64_1_fu_491_p1;

assign lshr_ln70_1_fu_912_p2 = DCAC_temp_q1 >> zext_ln70_1_fu_909_p1;

assign lshr_ln70_fu_828_p2 = DCAC_temp_q1 >> zext_ln70_fu_825_p1;

assign lshr_ln71_1_fu_925_p2 = DCAC_temp_q0 >> zext_ln71_3_fu_922_p1;

assign lshr_ln71_fu_841_p2 = DCAC_temp_q0 >> zext_ln71_1_fu_838_p1;

assign lshr_ln85_1_fu_663_p2 = DCAC_temp_q1 >> zext_ln85_3_fu_660_p1;

assign lshr_ln85_fu_526_p2 = DCAC_temp_q1 >> zext_ln85_1_fu_523_p1;

assign lshr_ln86_1_fu_676_p2 = DCAC_temp_q0 >> zext_ln86_3_fu_673_p1;

assign lshr_ln86_fu_539_p2 = DCAC_temp_q0 >> zext_ln86_1_fu_536_p1;

assign lshr_ln87_1_fu_719_p2 = DCAC_temp_q1 >> zext_ln87_3_fu_716_p1;

assign lshr_ln87_fu_558_p2 = DCAC_temp_q1 >> zext_ln87_1_fu_555_p1;

assign lshr_ln88_1_fu_732_p2 = DCAC_temp_q0 >> zext_ln88_3_fu_729_p1;

assign lshr_ln88_fu_571_p2 = DCAC_temp_q0 >> zext_ln88_1_fu_568_p1;

assign or_ln59_fu_1309_p2 = (empty_reg_1842_pp0_iter1_reg | 3'd1);

assign or_ln63_fu_581_p2 = (empty_59_reg_1851 | 2'd1);

assign sext_ln108_1_fu_1342_p1 = grp_fu_1798_p3;

assign sext_ln108_fu_982_p1 = grp_fu_1690_p3;

assign sext_ln111_1_fu_1274_p1 = add_ln111_2_reg_2310;

assign sext_ln111_fu_979_p1 = add_ln111_reg_2184;

assign sext_ln115_1_fu_1287_p1 = $signed(tmp10_1_fu_1282_p2);

assign sext_ln115_fu_1004_p1 = $signed(tmp10_fu_999_p2);

assign sext_ln116_1_fu_1165_p1 = xor_ln116_fu_1160_p2;

assign sext_ln116_2_fu_1358_p1 = $signed(add_ln115_2_reg_2359);

assign sext_ln116_3_fu_1534_p1 = $signed(add_ln116_fu_1529_p2);

assign sext_ln116_fu_1014_p1 = $signed(add_ln115_fu_1008_p2);

assign sext_ln117_1_fu_1397_p1 = $signed(tmp11_1_fu_1392_p2);

assign sext_ln117_fu_1055_p1 = $signed(tmp11_fu_1050_p2);

assign sext_ln118_1_fu_1580_p1 = zext_ln119_1_cast_fu_1572_p3;

assign sext_ln118_fu_1181_p1 = zext_ln119_cast_fu_1174_p3;

assign sext_ln121_fu_1561_p1 = xor_ln116_reg_2289;

assign sext_ln47_10_fu_958_p1 = $signed(tmp13_fu_952_p2);

assign sext_ln47_12_fu_793_p1 = tmp0_5_reg_2003;

assign sext_ln47_13_fu_796_p1 = tmp1_5_reg_2009;

assign sext_ln47_14_fu_799_p1 = tmp2_5_reg_2045;

assign sext_ln47_16_fu_812_p1 = tmp3_5_reg_2051;

assign sext_ln47_18_fu_1235_p1 = grp_fu_1788_p3;

assign sext_ln47_19_fu_1322_p1 = $signed(tmp13_1_reg_2348);

assign sext_ln47_1_fu_938_p1 = tmp3_reg_2073;

assign sext_ln47_3_fu_616_p1 = tmp0_1_reg_1926;

assign sext_ln47_4_fu_619_p1 = tmp1_1_reg_1932;

assign sext_ln47_5_fu_622_p1 = tmp2_1_reg_1948;

assign sext_ln47_7_fu_635_p1 = tmp3_1_reg_1954;

assign sext_ln47_9_fu_1319_p1 = tmp2_4_reg_2337;

assign sext_ln47_fu_935_p1 = tmp2_reg_2067;

assign sext_ln64_1_fu_707_p1 = tmp_13_cast_fu_695_p3;

assign sext_ln64_fu_425_p1 = tmp_4_cast_fu_412_p3;

assign sext_ln71_1_fu_1238_p1 = $signed(trunc_ln70_1_reg_2205);

assign sext_ln71_fu_882_p1 = $signed(trunc_ln70_reg_2116);

assign sext_ln73_1_fu_1241_p1 = $signed(trunc_ln71_1_reg_2210);

assign sext_ln73_fu_885_p1 = $signed(trunc_ln71_reg_2121);

assign sext_ln74_1_fu_1332_p1 = $signed(tmp1_4_fu_1325_p3);

assign sext_ln74_fu_969_p1 = $signed(tmp1_fu_962_p3);

assign sext_ln77_1_fu_1264_p1 = $signed(tmp0_4_fu_1256_p3);

assign sext_ln77_fu_948_p1 = $signed(tmp0_fu_941_p3);

assign sext_ln85_1_fu_594_p1 = tmp_s_fu_586_p3;

assign sext_ln85_fu_456_p1 = tmp_7_fu_449_p3;

assign sext_ln87_2_fu_505_p1 = tmp_7_reg_1888;

assign sext_ln87_3_fu_648_p1 = tmp_s_reg_1967;

assign sub_ln116_1_fu_1361_p2 = ($signed(sext_ln116_2_fu_1358_p1) - $signed(tmp3_7_reg_2353));

assign sub_ln116_fu_1018_p2 = ($signed(sext_ln116_fu_1014_p1) - $signed(tmp3_3_fu_994_p2));

assign sub_ln118_1_fu_1407_p2 = (add_ln117_2_fu_1401_p2 - tmp2_7_fu_1345_p2);

assign sub_ln118_fu_1065_p2 = (add_ln117_fu_1059_p2 - tmp2_3_fu_985_p2);

assign sub_ln120_1_fu_1445_p2 = (add_ln119_2_fu_1439_p2 - tmp1_7_fu_1354_p2);

assign sub_ln120_fu_1205_p2 = (add_ln119_reg_2240 - tmp1_3_fu_1197_p2);

assign sub_ln122_1_fu_1483_p2 = (add_ln121_2_fu_1477_p2 - tmp0_7_fu_1349_p2);

assign sub_ln122_fu_1109_p2 = (add_ln121_fu_1103_p2 - tmp0_3_fu_989_p2);

assign sub_ln74_1_fu_1244_p2 = ($signed(sext_ln71_1_fu_1238_p1) - $signed(sext_ln73_1_fu_1241_p1));

assign sub_ln74_fu_888_p2 = ($signed(sext_ln71_fu_882_p1) - $signed(sext_ln73_fu_885_p1));

assign tmp0_1_fu_532_p1 = lshr_ln85_fu_526_p2[15:0];

assign tmp0_3_fu_989_p2 = ($signed(z3_3_reg_2189) + $signed(sext_ln108_fu_982_p1));

assign tmp0_4_fu_1256_p3 = {{add_ln73_1_fu_1250_p2}, {13'd0}};

assign tmp0_5_fu_669_p1 = lshr_ln85_1_fu_663_p2[15:0];

assign tmp0_7_fu_1349_p2 = ($signed(z3_7_reg_2315) + $signed(sext_ln108_1_fu_1342_p1));

assign tmp0_fu_941_p3 = {{add_ln73_reg_2174}, {13'd0}};

assign tmp10_1_fu_1282_p2 = ($signed(grp_fu_1788_p3) + $signed(30'd1024));

assign tmp10_fu_999_p2 = ($signed(tmp3_reg_2073) + $signed(30'd1024));

assign tmp11_1_fu_1392_p2 = ($signed(tmp2_4_reg_2337) + $signed(31'd1024));

assign tmp11_fu_1050_p2 = ($signed(tmp2_reg_2067) + $signed(31'd1024));

assign tmp12_1_fu_1336_p2 = ($signed(sext_ln74_1_fu_1332_p1) - $signed(sext_ln47_9_fu_1319_p1));

assign tmp12_fu_973_p2 = ($signed(sext_ln74_fu_969_p1) - $signed(sext_ln47_fu_935_p1));

assign tmp13_1_fu_1268_p2 = ($signed(sext_ln77_1_fu_1264_p1) - $signed(sext_ln47_18_fu_1235_p1));

assign tmp13_fu_952_p2 = ($signed(sext_ln77_fu_948_p1) - $signed(sext_ln47_1_fu_938_p1));

assign tmp1_1_fu_545_p1 = lshr_ln86_fu_539_p2[15:0];

assign tmp1_3_fu_1197_p2 = ($signed(grp_fu_1772_p3) + $signed(z2_2_reg_2138));

assign tmp1_4_fu_1325_p3 = {{sub_ln74_1_reg_2343}, {13'd0}};

assign tmp1_5_fu_682_p1 = lshr_ln86_1_fu_676_p2[15:0];

assign tmp1_7_fu_1354_p2 = ($signed(grp_fu_1806_p3) + $signed(z2_5_reg_2283));

assign tmp1_fu_962_p3 = {{sub_ln74_reg_2169}, {13'd0}};

assign tmp2_1_fu_564_p1 = lshr_ln87_fu_558_p2[15:0];

assign tmp2_3_fu_985_p2 = ($signed(grp_fu_1698_p3) + $signed(z2_2_reg_2138));

assign tmp2_5_fu_725_p1 = lshr_ln87_1_fu_719_p2[15:0];

assign tmp2_7_fu_1345_p2 = ($signed(grp_fu_1814_p3) + $signed(z2_5_reg_2283));

assign tmp3_1_fu_577_p1 = lshr_ln88_fu_571_p2[15:0];

assign tmp3_3_fu_994_p2 = ($signed(grp_fu_1707_p3) + $signed(sext_ln111_fu_979_p1));

assign tmp3_5_fu_738_p1 = lshr_ln88_1_fu_732_p2[15:0];

assign tmp3_7_fu_1277_p2 = ($signed(z4_5_reg_2321) + $signed(sext_ln111_1_fu_1274_p1));

assign tmp_13_cast_fu_695_p3 = {{2'd2}, {or_ln63_reg_1960}};

assign tmp_15_cast_fu_855_p3 = {{3'd4}, {or_ln63_reg_1960}};

assign tmp_17_cast_fu_603_p3 = {{3'd5}, {or_ln63_fu_581_p2}};

assign tmp_1_fu_434_p3 = col_1_reg_1829[32'd2];

assign tmp_4_cast_fu_412_p3 = {{2'd2}, {empty_59_fu_408_p1}};

assign tmp_6_cast_fu_746_p3 = {{3'd4}, {empty_59_reg_1851}};

assign tmp_7_fu_449_p3 = {{1'd1}, {empty_59_reg_1851}};

assign tmp_8_cast_fu_465_p3 = {{3'd5}, {empty_59_reg_1851}};

assign tmp_fu_400_p3 = ap_sig_allocacmp_col_1[32'd3];

assign tmp_s_fu_586_p3 = {{1'd1}, {or_ln63_fu_581_p2}};

assign trunc_ln70_1_fu_918_p1 = lshr_ln70_1_fu_912_p2[15:0];

assign trunc_ln70_fu_834_p1 = lshr_ln70_fu_828_p2[15:0];

assign trunc_ln71_1_fu_931_p1 = lshr_ln71_1_fu_925_p2[15:0];

assign trunc_ln71_fu_847_p1 = lshr_ln71_fu_841_p2[15:0];

assign xor_ln116_fu_1160_p2 = (col_1_reg_1829 ^ 4'd8);

assign z2_3_fu_776_p1 = lshr_ln63_1_fu_770_p2[15:0];

assign z2_fu_487_p1 = lshr_ln63_fu_481_p2[15:0];

assign z3_1_fu_625_p2 = ($signed(sext_ln47_5_fu_622_p1) + $signed(sext_ln47_3_fu_616_p1));

assign z3_4_fu_789_p1 = lshr_ln64_1_fu_783_p2[15:0];

assign z3_5_fu_802_p2 = ($signed(sext_ln47_14_fu_799_p1) + $signed(sext_ln47_12_fu_793_p1));

assign z3_fu_501_p1 = lshr_ln64_fu_495_p2[15:0];

assign z4_3_fu_815_p2 = ($signed(sext_ln47_16_fu_812_p1) + $signed(sext_ln47_13_fu_796_p1));

assign z4_fu_638_p2 = ($signed(sext_ln47_7_fu_635_p1) + $signed(sext_ln47_4_fu_619_p1));

assign zext_ln116_1_fu_1538_p1 = $unsigned(sext_ln116_3_fu_1534_p1);

assign zext_ln116_fu_1169_p1 = $unsigned(sext_ln116_1_fu_1165_p1);

assign zext_ln117_1_fu_1556_p1 = add_ln117_4_fu_1550_p2;

assign zext_ln117_fu_1201_p1 = $unsigned(xor_ln116_reg_2289);

assign zext_ln118_1_fu_1584_p1 = $unsigned(sext_ln118_1_fu_1580_p1);

assign zext_ln118_fu_1185_p1 = $unsigned(sext_ln118_fu_1181_p1);

assign zext_ln119_1_cast_fu_1572_p3 = {{1'd1}, {zext_ln119_1_fu_1569_p1}};

assign zext_ln119_1_fu_1569_p1 = or_ln59_reg_2364;

assign zext_ln119_2_fu_1589_p1 = $unsigned(zext_ln119_1_cast_reg_2415);

assign zext_ln119_cast_fu_1174_p3 = {{1'd1}, {col_1_reg_1829}};

assign zext_ln119_fu_1546_p1 = $unsigned(zext_ln119_cast_reg_2295);

assign zext_ln120_1_fu_1598_p1 = add_ln120_1_fu_1593_p2;

assign zext_ln120_fu_1524_p1 = add_ln120_fu_1518_p2;

assign zext_ln121_1_fu_1608_p1 = add_ln121_4_fu_1603_p2;

assign zext_ln121_fu_1564_p1 = $unsigned(sext_ln121_fu_1561_p1);

assign zext_ln122_1_cast_fu_1613_p3 = {{2'd2}, {zext_ln119_1_reg_2410}};

assign zext_ln122_1_fu_1620_p1 = zext_ln122_1_cast_fu_1613_p3;

assign zext_ln122_cast_fu_1297_p3 = {{2'd2}, {col_1_reg_1829_pp0_iter1_reg}};

assign zext_ln122_fu_1304_p1 = zext_ln122_cast_fu_1297_p3;

assign zext_ln63_1_fu_420_p1 = $unsigned(tmp_4_cast_fu_412_p3);

assign zext_ln63_2_fu_1314_p1 = or_ln59_fu_1309_p2;

assign zext_ln63_3_fu_851_p1 = or_ln63_reg_1960;

assign zext_ln63_4_fu_477_p1 = and_ln_fu_441_p3;

assign zext_ln63_5_fu_702_p1 = $unsigned(tmp_13_cast_fu_695_p3);

assign zext_ln63_6_fu_767_p1 = and_ln_reg_1870;

assign zext_ln63_fu_742_p1 = empty_59_reg_1851;

assign zext_ln64_1_fu_491_p1 = and_ln_fu_441_p3;

assign zext_ln64_2_fu_711_p1 = $unsigned(sext_ln64_1_fu_707_p1);

assign zext_ln64_3_fu_780_p1 = and_ln_reg_1870;

assign zext_ln64_fu_429_p1 = $unsigned(sext_ln64_fu_425_p1);

assign zext_ln70_1_fu_909_p1 = and_ln_reg_1870;

assign zext_ln70_fu_825_p1 = and_ln_reg_1870;

assign zext_ln71_1_fu_838_p1 = and_ln_reg_1870;

assign zext_ln71_2_fu_862_p1 = tmp_15_cast_fu_855_p3;

assign zext_ln71_3_fu_922_p1 = and_ln_reg_1870;

assign zext_ln71_fu_753_p1 = tmp_6_cast_fu_746_p3;

assign zext_ln85_1_fu_523_p1 = and_ln_reg_1870;

assign zext_ln85_2_fu_598_p1 = $unsigned(sext_ln85_1_fu_594_p1);

assign zext_ln85_3_fu_660_p1 = and_ln_reg_1870;

assign zext_ln85_fu_460_p1 = $unsigned(sext_ln85_fu_456_p1);

assign zext_ln86_1_fu_536_p1 = and_ln_reg_1870;

assign zext_ln86_2_fu_611_p1 = tmp_17_cast_fu_603_p3;

assign zext_ln86_3_fu_673_p1 = and_ln_reg_1870;

assign zext_ln86_fu_472_p1 = tmp_8_cast_fu_465_p3;

assign zext_ln87_1_fu_555_p1 = and_ln_reg_1870;

assign zext_ln87_2_fu_651_p1 = $unsigned(sext_ln87_3_fu_648_p1);

assign zext_ln87_3_fu_716_p1 = and_ln_reg_1870;

assign zext_ln87_fu_508_p1 = $unsigned(sext_ln87_2_fu_505_p1);

assign zext_ln88_1_fu_568_p1 = and_ln_reg_1870;

assign zext_ln88_2_fu_656_p1 = $unsigned(tmp_s_reg_1967);

assign zext_ln88_3_fu_729_p1 = and_ln_reg_1870;

assign zext_ln88_fu_513_p1 = $unsigned(tmp_7_reg_1888);

always @ (posedge ap_clk) begin
    and_ln_reg_1870[3:0] <= 4'b0000;
    tmp_7_reg_1888[2] <= 1'b1;
    or_ln63_reg_1960[0] <= 1'b1;
    tmp_s_reg_1967[0] <= 1'b1;
    tmp_s_reg_1967[2] <= 1'b1;
    zext_ln119_cast_reg_2295[4] <= 1'b1;
    or_ln59_reg_2364[0] <= 1'b1;
    col_cast23_reg_2404[5:4] <= 2'b00;
    zext_ln119_1_reg_2410[0] <= 1'b1;
    zext_ln119_1_reg_2410[3] <= 1'b0;
    zext_ln119_1_cast_reg_2415[0] <= 1'b1;
    zext_ln119_1_cast_reg_2415[4:3] <= 2'b10;
end

endmodule //idct_Loop_VITIS_LOOP_59_2_proc
