-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity idct is
port (
    DCAC_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    blockout_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    DCAC_TVALID : IN STD_LOGIC;
    DCAC_TREADY : OUT STD_LOGIC;
    blockout_TVALID : OUT STD_LOGIC;
    blockout_TREADY : IN STD_LOGIC );
end;


architecture behav of idct is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "idct_idct,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.596625,HLS_SYN_LAT=58,HLS_SYN_TPT=59,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=7114,HLS_SYN_LUT=15307,HLS_VERSION=2022_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal Block_entry687_proc1_U0_ap_start : STD_LOGIC;
    signal Block_entry687_proc1_U0_ap_done : STD_LOGIC;
    signal Block_entry687_proc1_U0_ap_continue : STD_LOGIC;
    signal Block_entry687_proc1_U0_ap_idle : STD_LOGIC;
    signal Block_entry687_proc1_U0_ap_ready : STD_LOGIC;
    signal Block_entry687_proc1_U0_DCAC_TREADY : STD_LOGIC;
    signal Block_entry687_proc1_U0_blockout_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_entry687_proc1_U0_blockout_TVALID : STD_LOGIC;

    component idct_Block_entry687_proc1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        DCAC_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        DCAC_TVALID : IN STD_LOGIC;
        DCAC_TREADY : OUT STD_LOGIC;
        blockout_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        blockout_TVALID : OUT STD_LOGIC;
        blockout_TREADY : IN STD_LOGIC );
    end component;



begin
    Block_entry687_proc1_U0 : component idct_Block_entry687_proc1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_entry687_proc1_U0_ap_start,
        ap_done => Block_entry687_proc1_U0_ap_done,
        ap_continue => Block_entry687_proc1_U0_ap_continue,
        ap_idle => Block_entry687_proc1_U0_ap_idle,
        ap_ready => Block_entry687_proc1_U0_ap_ready,
        DCAC_TDATA => DCAC_TDATA,
        DCAC_TVALID => DCAC_TVALID,
        DCAC_TREADY => Block_entry687_proc1_U0_DCAC_TREADY,
        blockout_TDATA => Block_entry687_proc1_U0_blockout_TDATA,
        blockout_TVALID => Block_entry687_proc1_U0_blockout_TVALID,
        blockout_TREADY => blockout_TREADY);




    Block_entry687_proc1_U0_ap_continue <= ap_const_logic_1;
    Block_entry687_proc1_U0_ap_start <= ap_const_logic_1;
    DCAC_TREADY <= Block_entry687_proc1_U0_DCAC_TREADY;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    blockout_TDATA <= Block_entry687_proc1_U0_blockout_TDATA;
    blockout_TVALID <= Block_entry687_proc1_U0_blockout_TVALID;
end behav;
