// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="idct_idct,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.778500,HLS_SYN_LAT=194,HLS_SYN_TPT=76,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=2859,HLS_SYN_LUT=6608,HLS_VERSION=2022_1}" *)

module idct (
        ap_clk,
        ap_rst_n,
        DCAC_TDATA,
        blockout_TDATA,
        DCAC_TVALID,
        DCAC_TREADY,
        blockout_TVALID,
        blockout_TREADY
);


input   ap_clk;
input   ap_rst_n;
input  [15:0] DCAC_TDATA;
output  [7:0] blockout_TDATA;
input   DCAC_TVALID;
output   DCAC_TREADY;
output   blockout_TVALID;
input   blockout_TREADY;

 reg    ap_rst_n_inv;
wire   [31:0] DCAC_temp_i_q0;
wire   [31:0] DCAC_temp_i_q1;
wire   [3:0] DCAC_temp_t_we0;
wire   [31:0] DCAC_temp_t_q0;
wire   [31:0] DCAC_temp_t_q1;
wire   [20:0] workspace_i_q0;
wire   [20:0] workspace_i_q1;
wire   [20:0] workspace_t_q0;
wire   [20:0] workspace_t_q1;
wire    Loop_VITIS_LOOP_38_1_proc1_U0_ap_start;
wire    Loop_VITIS_LOOP_38_1_proc1_U0_ap_done;
wire    Loop_VITIS_LOOP_38_1_proc1_U0_ap_continue;
wire    Loop_VITIS_LOOP_38_1_proc1_U0_ap_idle;
wire    Loop_VITIS_LOOP_38_1_proc1_U0_ap_ready;
wire    Loop_VITIS_LOOP_38_1_proc1_U0_DCAC_TREADY;
wire   [4:0] Loop_VITIS_LOOP_38_1_proc1_U0_DCAC_temp_address0;
wire    Loop_VITIS_LOOP_38_1_proc1_U0_DCAC_temp_ce0;
wire   [3:0] Loop_VITIS_LOOP_38_1_proc1_U0_DCAC_temp_we0;
wire   [31:0] Loop_VITIS_LOOP_38_1_proc1_U0_DCAC_temp_d0;
wire    Loop_VITIS_LOOP_59_2_proc_U0_ap_start;
wire    Loop_VITIS_LOOP_59_2_proc_U0_ap_done;
wire    Loop_VITIS_LOOP_59_2_proc_U0_ap_continue;
wire    Loop_VITIS_LOOP_59_2_proc_U0_ap_idle;
wire    Loop_VITIS_LOOP_59_2_proc_U0_ap_ready;
wire   [4:0] Loop_VITIS_LOOP_59_2_proc_U0_DCAC_temp_address0;
wire    Loop_VITIS_LOOP_59_2_proc_U0_DCAC_temp_ce0;
wire   [4:0] Loop_VITIS_LOOP_59_2_proc_U0_DCAC_temp_address1;
wire    Loop_VITIS_LOOP_59_2_proc_U0_DCAC_temp_ce1;
wire   [5:0] Loop_VITIS_LOOP_59_2_proc_U0_workspace_address0;
wire    Loop_VITIS_LOOP_59_2_proc_U0_workspace_ce0;
wire    Loop_VITIS_LOOP_59_2_proc_U0_workspace_we0;
wire   [20:0] Loop_VITIS_LOOP_59_2_proc_U0_workspace_d0;
wire   [5:0] Loop_VITIS_LOOP_59_2_proc_U0_workspace_address1;
wire    Loop_VITIS_LOOP_59_2_proc_U0_workspace_ce1;
wire    Loop_VITIS_LOOP_59_2_proc_U0_workspace_we1;
wire   [20:0] Loop_VITIS_LOOP_59_2_proc_U0_workspace_d1;
wire    Loop_VITIS_LOOP_130_3_proc2_U0_ap_start;
wire    Loop_VITIS_LOOP_130_3_proc2_U0_ap_done;
wire    Loop_VITIS_LOOP_130_3_proc2_U0_ap_continue;
wire    Loop_VITIS_LOOP_130_3_proc2_U0_ap_idle;
wire    Loop_VITIS_LOOP_130_3_proc2_U0_ap_ready;
wire   [5:0] Loop_VITIS_LOOP_130_3_proc2_U0_workspace_address0;
wire    Loop_VITIS_LOOP_130_3_proc2_U0_workspace_ce0;
wire   [5:0] Loop_VITIS_LOOP_130_3_proc2_U0_workspace_address1;
wire    Loop_VITIS_LOOP_130_3_proc2_U0_workspace_ce1;
wire   [7:0] Loop_VITIS_LOOP_130_3_proc2_U0_blockout_TDATA;
wire    Loop_VITIS_LOOP_130_3_proc2_U0_blockout_TVALID;
wire    DCAC_temp_i_full_n;
wire    DCAC_temp_t_empty_n;
wire    workspace_i_full_n;
wire    workspace_t_empty_n;

idct_DCAC_temp_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
DCAC_temp_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_VITIS_LOOP_38_1_proc1_U0_DCAC_temp_address0),
    .i_ce0(Loop_VITIS_LOOP_38_1_proc1_U0_DCAC_temp_ce0),
    .i_we0(Loop_VITIS_LOOP_38_1_proc1_U0_DCAC_temp_we0),
    .i_d0(Loop_VITIS_LOOP_38_1_proc1_U0_DCAC_temp_d0),
    .i_q0(DCAC_temp_i_q0),
    .i_address1(5'd0),
    .i_ce1(1'b0),
    .i_q1(DCAC_temp_i_q1),
    .t_address0(Loop_VITIS_LOOP_59_2_proc_U0_DCAC_temp_address0),
    .t_ce0(Loop_VITIS_LOOP_59_2_proc_U0_DCAC_temp_ce0),
    .t_we0(DCAC_temp_t_we0),
    .t_d0(32'd0),
    .t_q0(DCAC_temp_t_q0),
    .t_address1(Loop_VITIS_LOOP_59_2_proc_U0_DCAC_temp_address1),
    .t_ce1(Loop_VITIS_LOOP_59_2_proc_U0_DCAC_temp_ce1),
    .t_q1(DCAC_temp_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(DCAC_temp_i_full_n),
    .i_write(Loop_VITIS_LOOP_38_1_proc1_U0_ap_done),
    .t_empty_n(DCAC_temp_t_empty_n),
    .t_read(Loop_VITIS_LOOP_59_2_proc_U0_ap_ready)
);

idct_workspace_RAM_AUTO_1R1W #(
    .DataWidth( 21 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
workspace_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_VITIS_LOOP_59_2_proc_U0_workspace_address0),
    .i_ce0(Loop_VITIS_LOOP_59_2_proc_U0_workspace_ce0),
    .i_we0(Loop_VITIS_LOOP_59_2_proc_U0_workspace_we0),
    .i_d0(Loop_VITIS_LOOP_59_2_proc_U0_workspace_d0),
    .i_q0(workspace_i_q0),
    .i_address1(Loop_VITIS_LOOP_59_2_proc_U0_workspace_address1),
    .i_ce1(Loop_VITIS_LOOP_59_2_proc_U0_workspace_ce1),
    .i_we1(Loop_VITIS_LOOP_59_2_proc_U0_workspace_we1),
    .i_d1(Loop_VITIS_LOOP_59_2_proc_U0_workspace_d1),
    .i_q1(workspace_i_q1),
    .t_address0(Loop_VITIS_LOOP_130_3_proc2_U0_workspace_address0),
    .t_ce0(Loop_VITIS_LOOP_130_3_proc2_U0_workspace_ce0),
    .t_we0(1'b0),
    .t_d0(21'd0),
    .t_q0(workspace_t_q0),
    .t_address1(Loop_VITIS_LOOP_130_3_proc2_U0_workspace_address1),
    .t_ce1(Loop_VITIS_LOOP_130_3_proc2_U0_workspace_ce1),
    .t_we1(1'b0),
    .t_d1(21'd0),
    .t_q1(workspace_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(workspace_i_full_n),
    .i_write(Loop_VITIS_LOOP_59_2_proc_U0_ap_done),
    .t_empty_n(workspace_t_empty_n),
    .t_read(Loop_VITIS_LOOP_130_3_proc2_U0_ap_ready)
);

idct_Loop_VITIS_LOOP_38_1_proc1 Loop_VITIS_LOOP_38_1_proc1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_VITIS_LOOP_38_1_proc1_U0_ap_start),
    .ap_done(Loop_VITIS_LOOP_38_1_proc1_U0_ap_done),
    .ap_continue(Loop_VITIS_LOOP_38_1_proc1_U0_ap_continue),
    .ap_idle(Loop_VITIS_LOOP_38_1_proc1_U0_ap_idle),
    .ap_ready(Loop_VITIS_LOOP_38_1_proc1_U0_ap_ready),
    .DCAC_TVALID(DCAC_TVALID),
    .DCAC_TDATA(DCAC_TDATA),
    .DCAC_TREADY(Loop_VITIS_LOOP_38_1_proc1_U0_DCAC_TREADY),
    .DCAC_temp_address0(Loop_VITIS_LOOP_38_1_proc1_U0_DCAC_temp_address0),
    .DCAC_temp_ce0(Loop_VITIS_LOOP_38_1_proc1_U0_DCAC_temp_ce0),
    .DCAC_temp_we0(Loop_VITIS_LOOP_38_1_proc1_U0_DCAC_temp_we0),
    .DCAC_temp_d0(Loop_VITIS_LOOP_38_1_proc1_U0_DCAC_temp_d0)
);

idct_Loop_VITIS_LOOP_59_2_proc Loop_VITIS_LOOP_59_2_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_VITIS_LOOP_59_2_proc_U0_ap_start),
    .ap_done(Loop_VITIS_LOOP_59_2_proc_U0_ap_done),
    .ap_continue(Loop_VITIS_LOOP_59_2_proc_U0_ap_continue),
    .ap_idle(Loop_VITIS_LOOP_59_2_proc_U0_ap_idle),
    .ap_ready(Loop_VITIS_LOOP_59_2_proc_U0_ap_ready),
    .DCAC_temp_address0(Loop_VITIS_LOOP_59_2_proc_U0_DCAC_temp_address0),
    .DCAC_temp_ce0(Loop_VITIS_LOOP_59_2_proc_U0_DCAC_temp_ce0),
    .DCAC_temp_q0(DCAC_temp_t_q0),
    .DCAC_temp_address1(Loop_VITIS_LOOP_59_2_proc_U0_DCAC_temp_address1),
    .DCAC_temp_ce1(Loop_VITIS_LOOP_59_2_proc_U0_DCAC_temp_ce1),
    .DCAC_temp_q1(DCAC_temp_t_q1),
    .workspace_address0(Loop_VITIS_LOOP_59_2_proc_U0_workspace_address0),
    .workspace_ce0(Loop_VITIS_LOOP_59_2_proc_U0_workspace_ce0),
    .workspace_we0(Loop_VITIS_LOOP_59_2_proc_U0_workspace_we0),
    .workspace_d0(Loop_VITIS_LOOP_59_2_proc_U0_workspace_d0),
    .workspace_address1(Loop_VITIS_LOOP_59_2_proc_U0_workspace_address1),
    .workspace_ce1(Loop_VITIS_LOOP_59_2_proc_U0_workspace_ce1),
    .workspace_we1(Loop_VITIS_LOOP_59_2_proc_U0_workspace_we1),
    .workspace_d1(Loop_VITIS_LOOP_59_2_proc_U0_workspace_d1)
);

idct_Loop_VITIS_LOOP_130_3_proc2 Loop_VITIS_LOOP_130_3_proc2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_VITIS_LOOP_130_3_proc2_U0_ap_start),
    .ap_done(Loop_VITIS_LOOP_130_3_proc2_U0_ap_done),
    .ap_continue(Loop_VITIS_LOOP_130_3_proc2_U0_ap_continue),
    .ap_idle(Loop_VITIS_LOOP_130_3_proc2_U0_ap_idle),
    .ap_ready(Loop_VITIS_LOOP_130_3_proc2_U0_ap_ready),
    .blockout_TREADY(blockout_TREADY),
    .workspace_address0(Loop_VITIS_LOOP_130_3_proc2_U0_workspace_address0),
    .workspace_ce0(Loop_VITIS_LOOP_130_3_proc2_U0_workspace_ce0),
    .workspace_q0(workspace_t_q0),
    .workspace_address1(Loop_VITIS_LOOP_130_3_proc2_U0_workspace_address1),
    .workspace_ce1(Loop_VITIS_LOOP_130_3_proc2_U0_workspace_ce1),
    .workspace_q1(workspace_t_q1),
    .blockout_TDATA(Loop_VITIS_LOOP_130_3_proc2_U0_blockout_TDATA),
    .blockout_TVALID(Loop_VITIS_LOOP_130_3_proc2_U0_blockout_TVALID)
);

assign DCAC_TREADY = Loop_VITIS_LOOP_38_1_proc1_U0_DCAC_TREADY;

assign DCAC_temp_t_we0 = 1'b0;

assign Loop_VITIS_LOOP_130_3_proc2_U0_ap_continue = 1'b1;

assign Loop_VITIS_LOOP_130_3_proc2_U0_ap_start = workspace_t_empty_n;

assign Loop_VITIS_LOOP_38_1_proc1_U0_ap_continue = DCAC_temp_i_full_n;

assign Loop_VITIS_LOOP_38_1_proc1_U0_ap_start = 1'b1;

assign Loop_VITIS_LOOP_59_2_proc_U0_ap_continue = workspace_i_full_n;

assign Loop_VITIS_LOOP_59_2_proc_U0_ap_start = DCAC_temp_t_empty_n;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign blockout_TDATA = Loop_VITIS_LOOP_130_3_proc2_U0_blockout_TDATA;

assign blockout_TVALID = Loop_VITIS_LOOP_130_3_proc2_U0_blockout_TVALID;

endmodule //idct
