// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module idct_Loop_DCAC_row_copy_proc1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        DCAC_TVALID,
        DCAC_TDATA,
        DCAC_TREADY,
        DCAC_temp_address0,
        DCAC_temp_ce0,
        DCAC_temp_we0,
        DCAC_temp_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   DCAC_TVALID;
input  [31:0] DCAC_TDATA;
output   DCAC_TREADY;
output  [4:0] DCAC_temp_address0;
output   DCAC_temp_ce0;
output  [3:0] DCAC_temp_we0;
output  [31:0] DCAC_temp_d0;

reg ap_idle;
reg DCAC_temp_ce0;
reg[3:0] DCAC_temp_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln33_fu_112_p2;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    DCAC_TDATA_blk_n;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln35_fu_127_p2;
reg   [0:0] icmp_ln35_reg_284;
reg    ap_block_pp0_stage0_11001;
wire   [1:0] trunc_ln35_1_fu_141_p1;
reg   [1:0] trunc_ln35_1_reg_289;
wire   [0:0] tmp_fu_145_p3;
reg   [0:0] tmp_reg_294;
wire   [31:0] shl_ln38_fu_183_p2;
reg   [31:0] shl_ln38_reg_299;
wire   [63:0] zext_ln38_1_fu_232_p1;
reg   [3:0] c_fu_64;
wire   [3:0] add_ln35_fu_189_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_c_load;
reg   [3:0] r_fu_68;
wire   [3:0] select_ln33_1_fu_214_p3;
reg    ap_loop_init_pp0_iter1_reg;
reg   [3:0] ap_sig_allocacmp_r_load;
reg   [6:0] indvar_flatten_fu_72;
wire   [6:0] add_ln33_1_fu_118_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [3:0] shl_ln38_1_fu_248_p2;
wire   [3:0] select_ln33_fu_133_p3;
wire   [4:0] and_ln_fu_153_p3;
wire   [31:0] zext_ln38_fu_161_p1;
wire   [31:0] lshr_ln38_fu_165_p2;
wire   [15:0] trunc_ln38_fu_171_p1;
wire   [31:0] zext_ln38_3_fu_179_p1;
wire   [31:0] zext_ln38_2_fu_175_p1;
wire   [3:0] add_ln33_fu_208_p2;
wire   [2:0] trunc_ln35_fu_221_p1;
wire   [4:0] tmp_1_fu_225_p3;
wire   [1:0] udiv_cast_cast_fu_237_p3;
wire   [3:0] zext_ln38_4_fu_244_p1;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    regslice_both_DCAC_U_apdone_blk;
wire   [31:0] DCAC_TDATA_int_regslice;
wire    DCAC_TVALID_int_regslice;
reg    DCAC_TREADY_int_regslice;
wire    regslice_both_DCAC_U_ack_in;
reg    ap_condition_100;
reg    ap_condition_112;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

idct_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

idct_regslice_both #(
    .DataWidth( 32 ))
regslice_both_DCAC_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(DCAC_TDATA),
    .vld_in(DCAC_TVALID),
    .ack_in(regslice_both_DCAC_U_ack_in),
    .data_out(DCAC_TDATA_int_regslice),
    .vld_out(DCAC_TVALID_int_regslice),
    .ack_out(DCAC_TREADY_int_regslice),
    .apdone_blk(regslice_both_DCAC_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_100)) begin
        if ((icmp_ln33_fu_112_p2 == 1'd0)) begin
            c_fu_64 <= add_ln35_fu_189_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_64 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_100)) begin
        if ((icmp_ln33_fu_112_p2 == 1'd0)) begin
            indvar_flatten_fu_72 <= add_ln33_1_fu_118_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_72 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_112)) begin
        r_fu_68 <= select_ln33_1_fu_214_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln33_fu_112_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln35_reg_284 <= icmp_ln35_fu_127_p2;
        shl_ln38_reg_299 <= shl_ln38_fu_183_p2;
        tmp_reg_294 <= select_ln33_fu_133_p3[32'd2];
        trunc_ln35_1_reg_289 <= trunc_ln35_1_fu_141_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0) & (icmp_ln33_fu_112_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCAC_TDATA_blk_n = DCAC_TVALID_int_regslice;
    end else begin
        DCAC_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln33_fu_112_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCAC_TREADY_int_regslice = 1'b1;
    end else begin
        DCAC_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCAC_temp_ce0 = 1'b1;
    end else begin
        DCAC_temp_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCAC_temp_we0 = shl_ln38_1_fu_248_p2;
    end else begin
        DCAC_temp_we0 = 4'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln33_fu_112_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_load = 4'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_64;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
        ap_sig_allocacmp_r_load = 4'd0;
    end else begin
        ap_sig_allocacmp_r_load = r_fu_68;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign DCAC_TREADY = regslice_both_DCAC_U_ack_in;

assign DCAC_temp_address0 = zext_ln38_1_fu_232_p1;

assign DCAC_temp_d0 = shl_ln38_reg_299;

assign add_ln33_1_fu_118_p2 = (ap_sig_allocacmp_indvar_flatten_load + 7'd1);

assign add_ln33_fu_208_p2 = (ap_sig_allocacmp_r_load + 4'd1);

assign add_ln35_fu_189_p2 = (select_ln33_fu_133_p3 + 4'd1);

assign and_ln_fu_153_p3 = {{tmp_fu_145_p3}, {4'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | ((icmp_ln33_fu_112_p2 == 1'd0) & (1'b0 == DCAC_TVALID_int_regslice)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | ((icmp_ln33_fu_112_p2 == 1'd0) & (1'b0 == DCAC_TVALID_int_regslice)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | ((icmp_ln33_fu_112_p2 == 1'd0) & (1'b0 == DCAC_TVALID_int_regslice)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_100 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_112 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln33_fu_112_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_127_p2 = ((ap_sig_allocacmp_c_load == 4'd8) ? 1'b1 : 1'b0);

assign lshr_ln38_fu_165_p2 = DCAC_TDATA_int_regslice >> zext_ln38_fu_161_p1;

assign select_ln33_1_fu_214_p3 = ((icmp_ln35_reg_284[0:0] == 1'b1) ? add_ln33_fu_208_p2 : ap_sig_allocacmp_r_load);

assign select_ln33_fu_133_p3 = ((icmp_ln35_fu_127_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_c_load);

assign shl_ln38_1_fu_248_p2 = 4'd3 << zext_ln38_4_fu_244_p1;

assign shl_ln38_fu_183_p2 = zext_ln38_3_fu_179_p1 << zext_ln38_2_fu_175_p1;

assign tmp_1_fu_225_p3 = {{trunc_ln35_fu_221_p1}, {trunc_ln35_1_reg_289}};

assign tmp_fu_145_p3 = select_ln33_fu_133_p3[32'd2];

assign trunc_ln35_1_fu_141_p1 = select_ln33_fu_133_p3[1:0];

assign trunc_ln35_fu_221_p1 = select_ln33_1_fu_214_p3[2:0];

assign trunc_ln38_fu_171_p1 = lshr_ln38_fu_165_p2[15:0];

assign udiv_cast_cast_fu_237_p3 = {{tmp_reg_294}, {1'd0}};

assign zext_ln38_1_fu_232_p1 = tmp_1_fu_225_p3;

assign zext_ln38_2_fu_175_p1 = and_ln_fu_153_p3;

assign zext_ln38_3_fu_179_p1 = trunc_ln38_fu_171_p1;

assign zext_ln38_4_fu_244_p1 = udiv_cast_cast_fu_237_p3;

assign zext_ln38_fu_161_p1 = and_ln_fu_153_p3;

endmodule //idct_Loop_DCAC_row_copy_proc1
