# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/j54mao/ECE423/ECE-423-Labs/ece423_prefab/ece423_prefab/lab_prefab/lab_prefab.srcs/sources_1/bd/lab_prefab/ip/lab_prefab_ps7_0_0/lab_prefab_ps7_0_0.xci
# IP: The module: 'lab_prefab_ps7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/j54mao/ECE423/ECE-423-Labs/ece423_prefab/ece423_prefab/lab_prefab/lab_prefab.gen/sources_1/bd/lab_prefab/ip/lab_prefab_ps7_0_0/lab_prefab_ps7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_prefab_ps7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/j54mao/ECE423/ECE-423-Labs/ece423_prefab/ece423_prefab/lab_prefab/lab_prefab.srcs/sources_1/bd/lab_prefab/ip/lab_prefab_ps7_0_0/lab_prefab_ps7_0_0.xci
# IP: The module: 'lab_prefab_ps7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/j54mao/ECE423/ECE-423-Labs/ece423_prefab/ece423_prefab/lab_prefab/lab_prefab.gen/sources_1/bd/lab_prefab/ip/lab_prefab_ps7_0_0/lab_prefab_ps7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_prefab_ps7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
