// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="idct_idct,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.596625,HLS_SYN_LAT=58,HLS_SYN_TPT=59,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=7114,HLS_SYN_LUT=15307,HLS_VERSION=2022_1}" *)

module idct (
        DCAC_TDATA,
        blockout_TDATA,
        ap_clk,
        ap_rst_n,
        DCAC_TVALID,
        DCAC_TREADY,
        blockout_TVALID,
        blockout_TREADY
);


input  [31:0] DCAC_TDATA;
output  [31:0] blockout_TDATA;
input   ap_clk;
input   ap_rst_n;
input   DCAC_TVALID;
output   DCAC_TREADY;
output   blockout_TVALID;
input   blockout_TREADY;

 reg    ap_rst_n_inv;
wire    Block_entry687_proc1_U0_ap_start;
wire    Block_entry687_proc1_U0_ap_done;
wire    Block_entry687_proc1_U0_ap_continue;
wire    Block_entry687_proc1_U0_ap_idle;
wire    Block_entry687_proc1_U0_ap_ready;
wire    Block_entry687_proc1_U0_DCAC_TREADY;
wire   [31:0] Block_entry687_proc1_U0_blockout_TDATA;
wire    Block_entry687_proc1_U0_blockout_TVALID;

idct_Block_entry687_proc1 Block_entry687_proc1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry687_proc1_U0_ap_start),
    .ap_done(Block_entry687_proc1_U0_ap_done),
    .ap_continue(Block_entry687_proc1_U0_ap_continue),
    .ap_idle(Block_entry687_proc1_U0_ap_idle),
    .ap_ready(Block_entry687_proc1_U0_ap_ready),
    .DCAC_TDATA(DCAC_TDATA),
    .DCAC_TVALID(DCAC_TVALID),
    .DCAC_TREADY(Block_entry687_proc1_U0_DCAC_TREADY),
    .blockout_TDATA(Block_entry687_proc1_U0_blockout_TDATA),
    .blockout_TVALID(Block_entry687_proc1_U0_blockout_TVALID),
    .blockout_TREADY(blockout_TREADY)
);

assign Block_entry687_proc1_U0_ap_continue = 1'b1;

assign Block_entry687_proc1_U0_ap_start = 1'b1;

assign DCAC_TREADY = Block_entry687_proc1_U0_DCAC_TREADY;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign blockout_TDATA = Block_entry687_proc1_U0_blockout_TDATA;

assign blockout_TVALID = Block_entry687_proc1_U0_blockout_TVALID;


reg find_kernel_block = 0;
// synthesis translate_off
`include "idct_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //idct

